### PR TITLE
Add GHA for pages build

### LINKED ISSUE #1: Interact with DW's actions template
Figure out how best to make this interact with actions template, put together by @davidwilby :

https://github.com/davidwilby/quarto-presentation-template

### PR DESCRIPTION
**Pull request by davidwyld**
add github actions workflow for pages build and notes on template repos to readme

resolves #1

### CODE REVIEW

**Review by thomaszwagerman — CHANGES_REQUESTED** [review]
I think in `pages.yml` line 20  "index.qmd" might need to be replaced with "template.qmd". 

Another caveat is that `template.qmd` is automatically renamed to the user's directory when `quarto use template antarctica/basdoc` is used. I think it might need pointing out in the README that `quarto render index.qmd --output-dir build` will need to be updated (like `quarto render <YOUR-DIRECTORY>.qmd --output-dir build`) for this to work.

What do you think the best approach would be?

**Comment by davidwyld** [comment]
Ah yes, interesting. I suppose this depends on how you envision users making use of this. I was sort of imagining two different routes:

1. **Purely as a Quarto template** (without gh actions) - via `quarto use ...` or `quarto add ...` as described in the README, which would change the name of `template.qmd`, right?
2. **As a GitHub template** (including gh actions) - via `Use this template` button on GitHub, which would copy the file contents of the repo, without changing the name.

Does `template.qmd` need to have that exact name? From the perspective of a GH template, it feels slightly awkward to have a file called `template.qmd` and I imagine users might change it.

Could we run `quarto render *.qmd` - or is that dangerous?

We could just include a note for the user to rename in the workflow yaml?

**Comment by thomaszwagerman** [comment]
I agree with having two different routes. 

re: 1) Yes, `quarto use...` renames `template.qmd` to the user directory, but `quarto add...` does not serve it.

From the [docs](https://quarto.org/docs/extensions/formats.html#format-templates) I can't tell if `template.qmd` specifically requires to be named as such. Renaming is handled by the quarto-cli, and not the extension itself, so without diving into that code (or trying it) not sure we can find out quickly.

I like the `quarto render *.qmd` solution because it enables both 1 & 2 to work out of the box. For a repository that is strictly a quarto revealjs presentation I don't _think_ it is dangerous? As soon as you start having multiple files referenced in an `index.qmd` I suppose it becomes a website, which requires a different approach.

**Comment by davidwyld** [comment]
My reading of [this section](https://quarto.org/docs/extensions/formats.html#format-templates) of the docs is that the file does need to be called `template.qmd` so let's go with the `quarto render *.qmd` in the workflow and add a note for users to change it.

**Review by thomaszwagerman — APPROVED** [review]

**Pull request merged**
